name: Metrics

on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generar metriques 
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_details: percentage